apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s4bbve2yw-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e86c94b1eda3c17fb40880d6dd9344488ef4d253@sha256:794b297f22a9704f96c9a89f0c472c36d99bb24e7ed862459f0f750b1af0fae1
          name: container-image
